language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
install:
  - rustup component add rustfmt-preview
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - env: FMT=true
      rust: beta
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - \[ ${FMT+x} ] \&& cargo fmt -- --check || [ ! ${FMT+x} ]
